version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    target-branch: main
    labels: [auto-dependencies]
    groups:
      all-minor-and-patch:
        patterns: ["*"]
        update-types:
          - "minor"
          - "patch"
    open-pull-requests-limit: 10

  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels: [auto-dependencies]
    groups:
      docker-deps:
        patterns: ["*"]
    open-pull-requests-limit: 5

  - package-ecosystem: gitsubmodule
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels: [auto-dependencies]
    groups:
      submodules:
        patterns: ["*"]
    open-pull-requests-limit: 10
