[workspace]
resolver = "2"
members = ["src/tracer", "src/ebpf", "src/tracer-installer"]
default-members = ["src/tracer", "src/ebpf", "src/tracer-installer"]

[workspace.package]
version = "2025.5.15+1"
edition = "2021"
authors = ["Tracer <info@tracer.cloud>"]
homepage = "https://tracer.cloud/"
repository = "https://github.com/Tracer-Cloud/tracer-client/"

[workspace.dependencies]
tracer_ebpf = { path = "src/ebpf" }

anyhow = "1.0.100"
assert_cmd = "2.0.17"
async-trait = "0.1.89"
aws-config = { version = "1.8.8", features = ["behavior-version-latest"] }
aws-credential-types = "1.2.8"
aws-sdk-ec2 = "1.175.1"
aws-sdk-pricing = "1.90.0"
aws-sdk-s3 = "1.108.0"
aws-sdk-secretsmanager = "1.90.0"
axum = "0.8.5"
bollard = "0.19.3"
built = { version = "0.8.0", features = ["chrono", "git2"] }
chrono = { version = "0.4.42", features = ["serde"] }
clap = { version = "4.5.49", features = ["derive", "env"] }
colored = "3.0.0"
config = { version = "0.15.17", default-features = false, features = [
    "toml",
    "convert-case",
] }
console = "0.16.1"
daemonize = "0.5.0"
dashmap = "6.1.0"
dialoguer = "0.12.0"
dirs-next = "2.0.0"
dotenvy = "0.15.7"
ec2_instance_metadata = { git = "https://github.com/Tracer-Cloud/ec2-instance-metadata-rs.git", branch = "master" }
enquote = "1.1.0"
flate2 = "1.1.4"
futures-util = "0.3.31"
git2 = { version = "0.20.2", features = [
    "https",
    "vendored-openssl",
], default-features = false }
indicatif = "0.18.0"
itertools = "0.14.0"
log = "0.4.28"
mockall = "0.13.1"
nix = { version = "0.30.1", features = ["user", "process", "fs"] }
octocrab = "0.44.1"
percent-encoding = "2.3.2"
pretty_assertions_sorted = "1.2.3"
rand = "0.9.2"
regex = "1.12.2"
reqwest = { version = "0.12.24", default-features = false, features = [
    "json",
    "rustls-tls",
    "stream",
] }
rstest = "0.26.1"
rustls = { version = "0.23.33", features = ["ring"] }
sentry = { version = "0.45.0", default-features = false, features = [
    "anyhow",
    "backtrace",
    "panic",
    "reqwest",
    "rustls",
] }
serde = { version = "1.0.219", features = ["std", "derive", "serde_derive"] }
serde_json = "1.0.145"
serde_regex = "1.1.0"
serial_test = "3.2.0"
shlex = "1.3.0"
softpath = "0.2.2"
sysinfo = "0.37.2"
tar = "0.4.44"
tempfile = "3.23.0"
termion = "4.0.5"
tokio = { version = "1.48.0", features = ["full"] }
tokio-retry = "0.3.0"
tokio-util = "0.7.16"
toml = "0.9.5"
tracing = { version = "0.1.41" }
tracing-appender = "0.2.3"
tracing-subscriber = { version = "0.3.20", features = [
    "env-filter",
    "json",
    "time",
    "local-time",
] }
typed-builder = "0.22.0"
url = "2.5.4"
uuid = { version = "1.18.1", features = [
    "v4",
    "fast-rng",
    "macro-diagnostics",
] }
which = "8.0.0"
yaml-rust2 = "0.10.4"
jsonwebtoken = "9.3.1"
once_cell = "1.21.3"
hyper = "1.7.0"

[profile.dev]
incremental = true

[profile.release]
lto = true
codegen-units = 1
