[workspace]
resolver = "2"
members = ["src/tracer", "src/ebpf", "src/tracer-installer"]
default-members = ["src/tracer", "src/ebpf", "src/tracer-installer"]

[workspace.package]
version = "2025.5.15+1"
edition = "2021"
authors = ["Tracer <info@tracer.cloud>"]
homepage = "http://tracer.cloud/"
repository = "https://github.com/Tracer-Cloud/tracer-client/"

[workspace.dependencies]
tracer = { path = "src/tracer" }


anyhow = "1.0.98"
chrono = { version = "0.4.38", features = ["serde"] }
clap = { version = "4.5.39", features = ["derive"] }
daemonize = "0.5"
log = "0.4.21"
octocrab = "0.44.0"
reqwest = { version = "0.12.13", default-features = false, features = [
    "json",
    "rustls-tls",
    "stream",
] }
serde = { version = "1.0", features = ["std", "derive", "serde_derive"] }
serde_json = "1.0.117"
sysinfo = "0.30"
tokio = { version = "1.45.0", features = ["full"] }
tokio-util = "0.7.15"
toml = "0.8.23"
tracing = { version = "0.1.40" }
tracing-appender = "0.2"
sqlx = { version = "0.8.3", features = [
    "runtime-tokio-rustls",
    "postgres",
    "chrono",
] }

ec2_instance_metadata = "0.3.0"
rand = "0.9.1"
uuid = { version = "1.17.0", features = [
    "v4",
    "fast-rng",
    "macro-diagnostics",
] }
once_cell = "1.21.3"

aws-config = { version = "1.6.3", features = ["behavior-version-latest"] }
aws-sdk-pricing = "1.74.0"
aws-sdk-s3 = "1.91.0"
aws-credential-types = "1.2.2"
aws-sdk-secretsmanager = "1.76.0"

tracing-subscriber = { version = "0.3.18", features = [
    "env-filter",
    "json",
    "time",
    "local-time",
] }
dirs = "6.0.0"
serde-query = "0.2.0"
itertools = "0.14.0"
percent-encoding = "2.3.1"
colored = "3.0.0"
axum = "0.8.3"
tempfile = "3.20.0"
config = { version = "0.15.11", default-features = false, features = [
    "toml",
    "convert-case",
] }
serial_test = "3.1.1"
dotenv = "0.15"
sentry = { version = "0.41.0", default-features = false, features = [
    "anyhow",
    "backtrace",
    "reqwest",
    "rustls",
    "panic",
] }
rstest = "0.25.0"
typed-builder = "0.21.0"
futures-util = "0.3"
dialoguer = "0.11.0"
console = "0.15.11"
mockall = "0.13.1"
regex = "1.0"
rustls = { version = "0.23.28", features = ["ring"] }
shlex = "1.3.0"
yaml-rust2 = "0.10.3"
pretty_assertions_sorted = "1.2.3"
