[workspace]
resolver = "2"
members = ["src/cli", "src/cloud_providers/aws", "src/daemon", "src/client", "src/extracts", "src/common", "integration_tests"]

[workspace.package]
name = "tracer"
version = "2025.4.11"
edition = "2021"
authors = ["Tracer <info@tracer.cloud>"]
homepage = "http://tracer.cloud/"
repository = "https://github.com/Tracer-Cloud/tracer-client/"

[workspace.dependencies]
tracer_aws = { path = "src/cloud_providers/aws" }
tracer_client = { path = "src/client" }
tracer_common = { path = "src/common" }
tracer_extracts = { path = "src/extracts" }
tracer_daemon = { path = "src/daemon" }
tracer_cli = { path = "src/cli" }

anyhow = "1.0.98"
chrono = { version = "0.4.38", features = ["serde"] }
clap = { version = "4.5.36", features = ["derive"] }
daemonize = "0.5"
homedir = "0.2.1"
lazy_static = "1.5.0"
log = "0.4.21"
octocrab = "0.44.0"
predicates = "3.1.2"
random-string = "1.1.0"
reqwest = { version = "0.12.13", default-features = false, features = ["json", "rustls-tls"] }
serde = { version = "1.0", features = ["std", "derive", "serde_derive"] }
serde_json = "1.0.117"
sysinfo = "0.30"
tokio = { version = "1.43.1", features = ["full"] }
tokio-util = "0.7.14"
toml = "0.8.14"
tracing = {version = "0.1.40"}
tracing-appender = "0.2"
url = "2.5.2"
linemux = "0.3.0"
tokio-stream = "0.1.15"
sqlx = { version = "0.8.3", features = ["runtime-tokio-rustls", "postgres", "chrono"] }

ec2_instance_metadata = "0.3.0"
rand = "0.8.5"
uuid = { version = "1.16.0", features = [ "v4", "fast-rng", "macro-diagnostics"] }
once_cell = "1.21.3"

aws-config = { version = "1.1.7", features = ["behavior-version-latest"] }
aws-sdk-s3 = "1.69.0"
aws-sdk-pricing = "1.64.0"
aws-credential-types = "1.2.2"
aws-sdk-secretsmanager = "1.65.0"

tracing-log = "0.2.0"
tracing-loki = {version = "0.2.5", default-features = false,  features = ["rustls", "compat-0-2-1"]}

tracing-subscriber = { version = "0.3.18", features = ["env-filter", "json", "time", "local-time"] }
dirs = "6.0.0"
serde-query = "0.2.0"
itertools = "0.14.0"
percent-encoding = "2.3.1"
walkdir = "2.5.0"
colored = "3.0.0"
axum = "0.8.3"
tempfile = "3.19.1"
config = { version = "0.15.11", default-features = false, features = ["toml", "convert-case"] }
serial_test = "3.1.1"
env_logger = "0.11"
dotenv = "0.15"
bollard = "0.18.1"
assert_cmd = "2.0"

typed-builder = "0.18"
futures-util = "0.3"

