# Base image aligned with Ubuntu ARM64
FROM ubuntu:24.04

# Install necessary dependencies for Rust, Localstack, Loki, and Grafana
RUN apt-get update && apt-get install -y \
    curl \
    wget \
    python3-pip \
    jq \
    git \
    build-essential \
    libssl-dev \
    pkg-config \
    && apt-get clean

# Install Rust
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"

# Install cargo-nextest for Rust testing
RUN cargo install cargo-nextest

# Install Localstack
RUN pip3 install localstack

# Install Loki (optional if you want to build and use binaries)
RUN wget https://github.com/grafana/loki/releases/download/v3.3.0/loki-linux-arm64.zip \
    && unzip loki-linux-arm64.zip -d /usr/bin/ \
    && rm loki-linux-arm64.zip

# Configure Grafana
RUN mkdir -p /etc/grafana/provisioning/datasources
RUN echo 'apiVersion: 1
datasources:
- name: Loki
  type: loki
  access: proxy
  orgId: 1
  url: http://localhost:3100
  basicAuth: false
  isDefault: true
  version: 1
  editable: false' > /etc/grafana/provisioning/datasources/ds.yaml

ENV GF_PATHS_PROVISIONING="/etc/grafana/provisioning" \
    GF_AUTH_ANONYMOUS_ENABLED="true" \
    GF_AUTH_ANONYMOUS_ORG_ROLE="Admin" \
    GF_FEATURE_TOGGLES_ENABLE="alertingSimplifiedRouting,alertingQueryAndExpressionsStepMode"

EXPOSE 3000 3100 4566

# Entrypoint script to run all services
COPY start.sh /start.sh
RUN chmod +x /start.sh
ENTRYPOINT ["/start.sh"]
