pipelines:
  - id: nf-core/rnaseq
    description: RNA sequencing analysis pipeline for gene/isoform quantification and extensive quality control.
    repo: https://github.com/nf-core/rnaseq
    language: nextflow
    version:
      min: 3.19.0
    subworkflows:
      - id: PREPARE_GENOME
        description: Create genome indexes for RNA-seq analysis.
        steps:
          - or:
              - task: GUNZIP_GTF
              - and:
                  - optional_task: GUNZIP_GFF
                  - task: GFFREAD
          - or:
              - task: STAR_GENOMEGENERATE
              - task: BBMAP_BBSPLIT
    tasks:
      - id: GUNZIP_GTF
        description: Unzip the GTF file.
        rules:
          - gunzip_gtf
      - id: GUNZIP_GFF
        description: Unzip the GFF file.
        rules:
          - gunzip_gff
      - id: GFFREAD
        description: Read the GFF file.
        rules:
          - gffread
      - id: BBMAP_BBSPLIT
        description: Split the FASTQ file into smaller chunks.
        rules:
          - bbsplit
          - jshell
      - id: STAR_GENOMEGENERATE
        description: Generate the genome index for STAR.
        rules:
          - STAR index
        optional_rules:
          - samtools faidx
    steps:
      - subworkflow: PREPARE_GENOME
