[package]
name = "tracer-installer"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]

anyhow = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
console = { workspace = true }
colored = { workspace = true }

async-trait = "0.1.88"
nix = { version = "0.30.1", features = ["user"]}
