[package]
name = "tracer-installer"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]

anyhow = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
console = { workspace = true }
colored = { workspace = true }
octocrab = { workspace = true }
futures-util = {workspace = true }
tempfile = {workspace = true }
dirs = {workspace = true }
clap = {workspace = true }

indicatif = "0.17"
async-trait = "0.1.88"
nix = { version = "0.30.1", features = ["user"]}
rustls = { version = "0.23.28", features = ["ring"] }
tar = "0.4.44"
flate2 = "1.1.2"
tokio-retry = "0.3.0"
