[package]
name = "tracer-installer"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]

anyhow = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
console = { workspace = true }
colored = { workspace = true }
octocrab = { workspace = true }
futures-util = {workspace = true }
tempfile = {workspace = true }
dirs = {workspace = true }
clap = {workspace = true }
rustls = {workspace = true }
tokio-retry = {workspace = true }
sentry = {workspace = true }

indicatif = "0.18.0"
async-trait = "0.1.88"
nix = { version = "0.30.1", features = ["user"]}

tar = "0.4.44"
flate2 = "1.1.2"
sysinfo = "0.35.2"