{
 "title": "CPU UTILIZATION BY PIPELINE",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "pipeline_name",
    "label": "Pipeline Name",
    "query": "select distinct data->>'pipeline_name' from batch_jobs_logs"
   }
  ]
 },
 "panels": [
  {
   "title": "Logs for $pipeline_name",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT data->>'message' as message\nfrom batch_jobs_logs\nWHERE data->>'pipeline_name' = '${pipeline_name}'\norder by creation_date desc;"
    }
   ]
  },
  {
   "title": "Processes called by job: $pipeline_name",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \n  data->'attributes'->>'tool_name' AS tool_name,\n  COUNT(DISTINCT data->'attributes'->'process'->>'tool_pid') AS execution_count\nFROM batch_jobs_logs\nWHERE data->>'pipeline_name' = '${pipeline_name}'\nGROUP BY tool_name\nORDER BY execution_count DESC;\n"
    }
   ]
  },
  {
   "title": "CPU UTILIZATION FOR JOB: $pipeline_name",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \n    to_timestamp((data->>'timestamp')::BIGINT) AS time,\n    (data->'attributes'->'system_metric'->>'system_cpu_utilization')::FLOAT AS cpu_usage\nFROM batch_jobs_logs\nWHERE data->>'pipeline_name' = '${pipeline_name}';"
    }
   ]
  },
  { "title": "Pipeline costs analisys", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 }, "repeat": "pipeline_name" },
  {
   "title": "Pipeline Runs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select COUNT(DISTINCT data->>'run_name') AS number_of_runs\nfrom batch_jobs_logs\nWHERE data->>'pipeline_name' = '$pipeline_name';\n"
    }
   ]
  },
  {
   "title": "Total costs of $pipeline_name pipelines",
   "type": "stat",
   "gridPos": { "h": 10, "w": 7, "x": 7, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH relevant_jobs AS (\n  SELECT DISTINCT job_id\n  FROM batch_jobs_logs\n  WHERE data->>'pipeline_name' = '${pipeline_name}'\n),\nrun_data AS (\n  SELECT \n    data->>'run_name' AS run_name,\n    data->>'run_id' AS run_id,\n    to_timestamp((data->>'timestamp')::BIGINT) AS ts,\n    (data->'attributes'->'system_properties'->>'ec2_cost_per_hour')::FLOAT AS cost_per_hour,\n    job_id\n  FROM batch_jobs_logs\n  WHERE job_id IN (SELECT job_id FROM relevant_jobs)\n),\nrun_times AS (\n  SELECT \n    job_id,\n    MIN(ts) AS start_time,\n    MAX(ts) AS end_time,\n    MAX(cost_per_hour) AS cost_per_hour -- Assuming cost remains constant for each run\n  FROM run_data\n  WHERE job_id IS NOT NULL\n  GROUP BY job_id\n),\ntotal_costs as (\n  SELECT \n    rt.job_id,\n    rt.start_time,\n    rt.end_time,\n    (EXTRACT(EPOCH FROM (rt.end_time - rt.start_time)) / 3600) * rt.cost_per_hour AS total_cost\n  FROM run_times rt\n)\nSELECT sum(total_cost) as total_costs\nfrom total_costs as tc;\n"
    }
   ]
  },
  {
   "title": "Total # of Processed Dataset for $pipeline_name",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH relevant_jobs AS (\n  SELECT DISTINCT job_id\n  FROM batch_jobs_logs\n  WHERE data->>'pipeline_name' = '${pipeline_name}'\n),\nrun_data AS (\n  SELECT \n    job_id,\n    COALESCE((data->'attributes'->'process_dataset_stats'->>'total')::INT, 0) AS processed_dataset\n  FROM batch_jobs_logs\n  WHERE job_id IN (SELECT job_id FROM relevant_jobs)\n),\nmax_per_run AS (\n  -- Take the maximum processed_dataset per job_id (each run)\n  SELECT \n    job_id,\n    MAX(processed_dataset) AS max_processed_dataset\n  FROM run_data\n  GROUP BY job_id\n)\nSELECT \n  SUM(max_processed_dataset) AS total_processed_datasets\nFROM max_per_run;\n"
    }
   ]
  },
  {
   "title": "$pipeline_name runs overview",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "rawSql": "WITH relevant_jobs AS (\n  SELECT DISTINCT job_id\n  FROM batch_jobs_logs\n  WHERE data->>'pipeline_name' = '${pipeline_name}'\n),\nrun_data AS (\n  SELECT \n    data->>'run_name' AS run_name,\n    data->>'run_id' AS run_id,\n    to_timestamp((data->>'timestamp')::BIGINT) AS ts,\n    (data->'attributes'->'system_properties'->>'ec2_cost_per_hour')::FLOAT AS cost_per_hour,\n    job_id,\n    COALESCE((data->'attributes'->'process_dataset_stats'->>'total')::INT, 0) AS processed_dataset\n  FROM batch_jobs_logs\n  WHERE job_id IN (SELECT job_id FROM relevant_jobs)\n),\nrun_times AS (\n  SELECT \n    job_id,\n    MIN(ts) AS start_time,\n    MAX(ts) AS end_time,\n    MAX(cost_per_hour) AS cost_per_hour,  -- Assuming cost remains constant for each run\n    MAX(processed_dataset) AS processed_dataset\n  FROM run_data\n  WHERE job_id IS NOT NULL\n  GROUP BY job_id\n)\nSELECT \n  rt.job_id AS run_name,\n  rt.start_time,\n  rt.end_time,\n  (EXTRACT(EPOCH FROM (rt.end_time - rt.start_time)) / 3600) * rt.cost_per_hour AS total_cost,\n  (EXTRACT(EPOCH FROM (rt.end_time - rt.start_time)) / 60) AS total_runtime_minutes,\n  CASE \n    WHEN rt.end_time < NOW() - INTERVAL '30 seconds' THEN 'Completed'\n    ELSE 'Running'\n  END AS status,\n  rt.processed_dataset AS processed_datasets\nFROM run_times rt\nORDER BY start_time DESC;\n"
    }
   ]
  }
 ]
}