use serde::{Deserialize, Serialize};

/*
Example of custom claims for the tracer jwt generated by Clerk:
{
    "email": "{{user.primary_email_address}}",
    "full_name": "{{user.full_name}}",
    "organization": "{{org.id}}"
}
*/

/// struct for the claims of the jwt token generated by Clerk
#[derive(Debug, Serialize, Deserialize)]
pub struct Claims {
    pub sub: String, // Subject - this will be the user id
    pub exp: usize,  // Expiration date
    pub iat: usize,  // Issued at

    // custom fields
    pub email: String,
    pub full_name: Option<String>, // for now the full name is optional
    pub organization: Option<String>, // also the organization is optional for now, until we have a better way to handle it
    pub organization_slug: String, //organization slug is required to generate the url for the run details page
}
