[package]
name = "tracer"

version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
authors = { workspace = true }

build = "build.rs"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
daemonize = { workspace = true }
octocrab = { workspace = true }
predicates = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
sqlx = { workspace = true }
colored = { workspace = true }
tracing-subscriber = { workspace = true }
tracing-appender = { workspace = true }
sentry = { workspace = true }
console = { workspace = true }
chrono = { workspace = true }
sysinfo = { workspace = true }
tracer_ebpf = { path = "../ebpf" }
itertools = { workspace = true }
once_cell = { workspace = true }
mockall = {workspace = true}
log = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
rand = { workspace = true }
uuid = { workspace = true }
dirs = { workspace = true }
percent-encoding = { workspace = true }
tokio-util = { workspace = true }
aws-config = { workspace = true }
aws-sdk-s3 = { workspace = true }
aws-sdk-pricing = { workspace = true }
aws-credential-types = { workspace = true }
aws-sdk-secretsmanager = { workspace = true }
serde-query = { workspace = true }
config = { workspace = true }
ec2_instance_metadata = { workspace = true }
axum = { workspace = true }
typed-builder = { workspace = true }
dialoguer = { workspace = true }
regex = { workspace = true }
rustls = { workspace = true }
yaml-rust2 = { workspace = true }

[dev-dependencies]
sqlx = { workspace = true }
dotenv = { workspace = true }
serial_test = { workspace = true }
uuid = { workspace = true }
