[package]
name = "typegen"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"

[[bin]]
name = "typegen"
path = "typegen.rs"
