name: Bioconda Tool Check

on:
  workflow_dispatch:

jobs:
  bioconda-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chunk: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install micromamba
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl
          curl -L https://micro.mamba.pm/api/micromamba/linux-64/latest \
            | tar -xvj -C /usr/local/bin --strip-components=1 bin/micromamba
          export MAMBA_ROOT_PREFIX=$HOME/micromamba
          export PATH="$MAMBA_ROOT_PREFIX/bin:$PATH"
          micromamba create -y -n bioenv -c conda-forge -c bioconda mamba

      - name: Setup environment
        run: |
          echo "MAMBA_ROOT_PREFIX=$HOME/micromamba" >> $GITHUB_ENV
          echo "PATH=$HOME/micromamba/bin:$PATH" >> $GITHUB_ENV
          echo "CHUNK_INDEX=${{ matrix.chunk }}" >> $GITHUB_ENV

      - name: Run Bioconda version check
        run: |
          set -euo pipefail
          mkdir -p logs

          # Inject this variable into the heredoc using Bash string interpolation:
          CHUNK_INDEX=${CHUNK_INDEX:-0}  # fallback to 0 if not set

          micromamba run -n bioenv bash <<EOF
          set -euo pipefail

          echo "Fetching Bioconda packages..."
          curl -s https://conda.anaconda.org/bioconda/linux-64/repodata.json -o linux64.json

          echo "Extracting unique tool names..."
          jq -r '.packages | keys[]' linux64.json \
            | sed -E 's/-[0-9][^-]*-[^-]*\\.(tar\\.bz2|conda)\$//' \
            | sort -u > packages.txt

          echo "Splitting into chunks..."
          split -n l/200 packages.txt chunk_

          CHUNK_LINE=\$(( $CHUNK_INDEX + 1 ))
          CHUNK_FILE=\$(find . -maxdepth 1 -name 'chunk_*' | sort | sed -n "\${CHUNK_LINE}p")
          echo "Processing \$CHUNK_FILE"

          TIMEOUT=20

          if [[ ! -f "\$CHUNK_FILE" ]]; then
            echo "Chunk file \$CHUNK_FILE not found"
            exit 1
          fi

          while read -r pkg; do
            echo "Installing \$pkg"
            ENV_NAME="biochk_\$pkg"

            if ! micromamba create -y -n "\$ENV_NAME" -c conda-forge -c bioconda "\$pkg" >/dev/null 2>&1; then
              echo "Installing \$pkg failed"
              echo "\$pkg: install failed" >> logs/errors_$CHUNK_INDEX.txt
              continue
            fi

            set +e
            # CMD_LIST=("\$pkg --version" "\$pkg -v" "\$pkg -V" "\$pkg --help" "\$pkg -h")
            CMD_LIST=("\$pkg")
            SUCCESS=0

            for CMD in "\${CMD_LIST[@]}"; do
              echo "Trying: \$CMD"
              OUTPUT=\$(timeout \$TIMEOUT micromamba run -n "\$ENV_NAME" \$CMD 2>&1)

              echo "\$OUTPUT"
            done

            set -e
            micromamba remove -y -n "\$ENV_NAME" --all >/dev/null 2>&1
          done < "\$CHUNK_FILE"
          EOF
