name: Rust CI
on:
  push:
    branches:
    - "main"
    - "staging"
  pull_request:
    branches:
    - "**"
env:
  CARGO_TERM_COLOR: always # Ensures colored output in GitHub Actions logs

jobs:
  build-and-test:
    name: Build and Test
    runs-on: linux-arm64-16c-64r-600ssd-ubuntu24

    services:
      localstack:
        image: localstack/localstack:4.0.3
        env:
          SERVICES: s3,
          AWS_REGION: us-east-2
          AWS_ACCESS_KEY_ID: 0
          AWS_SECRET_ACCESS_KEY: 0
          DEBUG: 1
        ports:
        - 4566:4566
    steps:
    - uses: actions/checkout@v4.1.4

    - name: Setup Rust toolchain
      run: rustup toolchain install stable --profile minimal

    - name: Rust Cache
      uses: Swatinem/rust-cache@v2.7.3

    - name: Set up cargo Nextest
      run: |
        which cargo-nextest || cargo install cargo-nextest

    - name: Build
      run: cargo build --verbose

    # - name: Copy config
    #   run: mkdir -p $HOME/.config/tracer && cp tracer.toml $HOME/.config/tracer/tracer.toml

    - name: Check Formatting
      run: cargo fmt -- --check

    - name: Lint with Clippy
      run: make clippy

    - name: Run tests
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: make test
