name: Rust Cargo Audit
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
jobs:
  cargo-audit:
    name: Cargo Audit
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository with submodules
        uses: actions/checkout@v4.1.4
        with:
          submodules: recursive # This will fetch all submodules recursively

      - name: Setup Rust toolchain
        run: |
          rustup toolchain install stable --profile minimal
          rustup toolchain install nightly-2025-04-15 --component rust-src
          rustup component add clippy
          rustup component add rustfmt

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y linux-headers-$(uname -r) libbpf-dev clang llvm

      - name: Install cargo audit
        run: cargo install cargo-audit

      - name: Run cargo audit
        run: cargo audit