name: Tests
on:
  push:
    branches:
      - main
      - dev
    paths:
      - "src/**"
      - ".github/workflows/build-and-test.yml"
  pull_request:
    branches:
      - main
      - dev
    paths:
      - "src/**"
      - ".github/workflows/build-and-test.yml"

env:
  CARGO_TERM_COLOR: always # Ensures colored output in GitHub Actions logs

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository with submodules
        uses: actions/checkout@v4.1.4
        with:
          submodules: recursive # This will fetch all submodules recursively

      - name: Setup Rust toolchain
        run: |
          rustup toolchain install stable --profile minimal
          rustup toolchain install nightly-2025-04-15 --component rust-src
          rustup component add clippy
          rustup component add rustfmt

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y linux-headers-$(uname -r) libbpf-dev clang llvm libssl-dev pkg-config

      - name: Run tests
        run: |
          cargo test --features test-bins
