name: Development Release On S3

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-release:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history and tags
          ref: main  # Use main branch after version update

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install target
        run: rustup target add x86_64-unknown-linux-gnu

      - name: Cache Rust dependencies
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: cargo-deps-x86_64-unknown-linux-gnu-stable-v1
          restore-keys: |
            cargo-deps-x86_64-unknown-linux-gnu-stable-

      - name: Cache build artifacts
        id: cache-build
        uses: actions/cache@v3
        with:
          path: |
            target/
          key: cargo-build-x86_64-unknown-linux-gnu-stable-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            cargo-build-x86_64-unknown-linux-gnu-stable-

      - name: Build the binary
        run: cargo build --release --target x86_64-unknown-linux-gnu
        env:
          CARGO_BUILD_TARGET: x86_64-unknown-linux-gnu

      - name: Prepare binary for release
        run: |
          mkdir -p release-files
          # Copy the binary to the release directory
          cp target/x86_64-unknown-linux-gnu/release/tracer release-files/tracer

          # Make the binary executable
          chmod +x release-files/tracer

          # Create tar.gz file with the desired name and correct file structure
          tar -czf release-files/tracer-x86_64-unknown-linux-gnu.tar.gz -C release-files tracer

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Upload to S3
        run: |
          aws s3 cp release-files/tracer-x86_64-unknown-linux-gnu.tar.gz s3://tracer-releases/tracer-x86_64-unknown-linux-gnu.tar.gz

  aws-batch-job-testing:
    needs: build-and-release
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Submit AWS Batch Job
        id: submit-batch-job
        run: |
          # Submit the batch job and capture the job ID
          JOB_ID=$(aws batch submit-job \
            --job-name "tracer-test-job" \
            --job-queue "NextflowCPU" \
            --job-definition "${{ secrets.AWS_BATCH_JOB_DEFINITION }}" \
            --query 'jobId' \
            --output text)
          
          echo "Job submitted with ID: $JOB_ID"
          echo "job_id=$JOB_ID" >> $GITHUB_OUTPUT

      - name: Wait for AWS Batch Job to complete
        id: wait-for-job
        run: |
          JOB_ID="${{ steps.submit-batch-job.outputs.job_id }}"
          echo "Waiting for job $JOB_ID to complete..."

          # Poll the job status until it's complete
          while true; do
            STATUS=$(aws batch describe-jobs --jobs $JOB_ID --query 'jobs[0].status' --output text)
            echo "Current job status: $STATUS"

            if [[ "$STATUS" == "SUCCEEDED" ]]; then
              echo "Job completed successfully!"
              echo "::set-output name=job_status::success"
              exit 0
            elif [[ "$STATUS" == "FAILED" ]]; then
              echo "::error::AWS Batch job $JOB_ID failed. Check AWS console for detailed logs."
              echo "::set-output name=job_status::failed"
              exit 1
            elif [[ "$STATUS" == "CANCELLED" || "$STATUS" == "TERMINATED" ]]; then
              echo "::error::AWS Batch job $JOB_ID was cancelled or terminated."
              echo "::set-output name=job_status::cancelled"
              exit 1
            fi

            echo "Waiting 30 seconds before checking again..."
            sleep 30
          done
