name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ github.ref_name }} \
            --draft \
            --title "${{ github.ref_name }}" \
            --notes "Release ${{ github.ref_name }}"

  upload-assets:
    needs: create-release
    permissions: write-all
    strategy:
      matrix:
        include:
          - target: aarch64-apple-darwin
            os: macos-latest
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: universal-apple-darwin
            os: macos-latest

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Restore Cache
        uses: actions/cache/restore@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: permanent-cargo-cache-${{ runner.os }}-${{ matrix.target }}
          restore-keys: |
            permanent-cargo-cache-${{ runner.os }}-${{ matrix.target }}

      - name: Install cross-compilation tools
        uses: taiki-e/setup-cross-toolchain-action@v1
        with:
          target: ${{ matrix.target }}
        if: startsWith(matrix.os, 'ubuntu')

      - name: Build Binary
        run: cargo build --release --target ${{ matrix.target }}

      - name: Package Binary
        run: |
          cd target/${{ matrix.target }}/release
          tar -czf ../../../tracer-${{ matrix.target }}.tar.gz tracer
          cd ../../..

      - name: Upload Binary
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ github.ref_name }} tracer-${{ matrix.target }}.tar.gz

      - name: Save Cache
        uses: actions/cache/save@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: permanent-cargo-cache-${{ runner.os }}-${{ matrix.target }}