name: Rollback Database Migrations

on:
  workflow_dispatch

jobs:
  rollback:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region us-east-1

      - name: Fetch Credentials
        run: |
          DB_SECRET=$(aws secretsmanager get-secret-value --secret-id '${{ secrets.DATABASE_SECRETS_ARN }}' --query SecretString --output text)
          DB_USER=$(echo $DB_SECRET | jq -r '.username')
          DB_PASS=$(echo $DB_SECRET | jq -r '.password')
          ENCODED_PASS=$(python3 -c "import urllib.parse; print(urllib.parse.quote('$DB_PASS'))")
          DB_HOST="${{ secrets.DATABASE_HOST }}"
          DB_NAME="tracer_db"

          # Store DB URL as an environment variable
          echo "DB_URL=postgres://$DB_USER:$ENCODED_PASS@$DB_HOST/$DB_NAME" >> $GITHUB_ENV

      - name: Run Rollback
        run: ./scripts/rollback.sh $DB_URL