name: Delete Branch S3 Assets

on:
  delete: # fires when any branch or tag is deleted

jobs:
  cleanup-s3-folder:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      BRANCH_NAME: ${{ github.event.ref }}
      
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Delete tracer releases s3
        run: |
          FOLDER="s3://tracer-releases/${BRANCH_NAME}/"
          aws s3 rm "$FOLDER" --recursive --quiet || true

      - name: Delete tracer installer releases s3
        run: |
          FOLDER="s3://tracer-installer-releases/${BRANCH_NAME}/"
          aws s3 rm "$FOLDER" --recursive --quiet || true
