name: Rust CI
on:
  pull_request:
    branches: 
      - "**"

env:
  CARGO_TERM_COLOR: always # Ensures colored output in GitHub Actions logs

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository with submodules
        uses: actions/checkout@v4.1.4
        with:
          submodules: recursive  # This will fetch all submodules recursively

      - name: Setup Rust toolchain
        run: |
          rustup toolchain install stable --profile minimal
          rustup toolchain install nightly-2025-04-15 --component rust-src
          rustup component add clippy
          rustup component add rustfmt

      - name: Set up cargo cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-${{ runner.os }}-${{ runner.arch }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-${{ runner.os }}-${{ runner.arch }}-cargo-


      - name: Install build dependencies
        run: |
          rustup toolchain install nightly-2025-04-15 --component rust-src
          
          # Install necessary eBPF dependencies
          sudo apt-get update
          sudo apt-get install -y linux-headers-$(uname -r) libbpf-dev clang llvm          

      - name: Cargo check
        run: cargo check --locked --all-targets