name: Semgrep Security Scanning

permissions:
  contents: read
  security-events: write

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * 6'  # weekly full scan

jobs:

  semgrep:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    steps:
      - uses: actions/checkout@v4.1.4
        with:
          fetch-depth: 0

      - name: Run Semgrep scan (Rust + OWASP)
        env:
          SEMGREP_SUPPRESS_ERRORS: true
        run: |
          semgrep ci --config "p/rust" --config "p/owasp-top-ten" --sarif --suppress-errors > semgrep.sarif || true

      - name: Upload SARIF report to GitHub Security tab
        if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
        uses: github/codeql-action/upload-sarif@v3.29.4
        with:
          sarif_file: semgrep.sarif
          category: semgrep


  # PR/Diff‑Aware Scan
  semgrep-pr:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    steps:
      - uses: actions/checkout@v4.1.4
        with:
          fetch-depth: 0

      - name: Run Semgrep diff-aware scan (Rust + OWASP)
        run: |
          semgrep ci \
            --config "p/rust" \
            --config "p/owasp-top-ten" \
            --sarif > semgrep-pr.sarif

      - uses: github/codeql-action/upload-sarif@v3.29.4
        with:
          sarif_file: semgrep-pr.sarif
          category: semgrep